In [23]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector

In [24]:
house=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets\\Housing.csv")
house

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [25]:
X=house.drop('price',axis=1)
y=house['price']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)

In [26]:
ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
transf=ColumnTransformer(transformers=[("OHE",ohe, make_column_selector
                                        (dtype_include=object))],remainder="passthrough",verbose_feature_names_out=False).set_output(transform="pandas")
X_trn_ohe=transf.fit_transform(X_train)
X_tst_ohe=transf.transform(X_test)

In [27]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsRegressor(n_neighbors=k) 
    knn.fit(X_trn_ohe,y_train)
    y_pred=knn.predict(X_tst_ohe)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=False)

    K     score
9  10  0.383108
8   9  0.377442
7   8  0.374427
5   6  0.371384
6   7  0.350074
4   5  0.326117
3   4  0.276338
2   3  0.211714
1   2  0.057812
0   1 -0.010284

In [28]:
scaler=StandardScaler().set_output(transform="pandas")

In [29]:
X_trn_scl=scaler.fit_transform(X_trn_ohe)#mean and SD
X_tst_scl=scaler.transform(X_tst_ohe)

In [30]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsRegressor(n_neighbors=k) 
    knn.fit(X_trn_scl,y_train)
    y_pred=knn.predict(X_tst_scl)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=True)

    K     score
0   1  0.470837
1   2  0.568237
2   3  0.656770
4   5  0.665637
3   4  0.669234
5   6  0.673463
7   8  0.681864
6   7  0.687105
8   9  0.692825
9  10  0.704812

In [33]:
min_max_scaler=MinMaxScaler()
transf_X_train=min_max_scaler.fit_transform(X_trn_ohe)
transf_X_test=min_max_scaler.transform(X_tst_ohe)

In [35]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsRegressor(n_neighbors=k) 
    knn.fit(transf_X_train,y_train)
    y_pred=knn.predict(transf_X_test)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=False)

    K     score
3   4  0.648484
5   6  0.634816
4   5  0.629438
2   3  0.617526
6   7  0.615586
8   9  0.613230
7   8  0.609255
9  10  0.609119
1   2  0.525986
0   1  0.332474