In [3]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector

In [4]:
concrete=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Concrete_Strength\\Concrete_Data.csv")
concrete

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [5]:
X=concrete.drop('Strength',axis=1)
y=concrete['Strength']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)

In [7]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsRegressor(n_neighbors=k) 
    knn.fit(X_train,y_train)
    y_pred=knn.predict(X_test)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=False)

    K     score
3   4  0.686443
4   5  0.677831
2   3  0.670443
5   6  0.664499
6   7  0.655339
7   8  0.654481
8   9  0.653360
9  10  0.650433
0   1  0.600760
1   2  0.585665

In [11]:
scaler=StandardScaler().set_output(transform="pandas")
X_trn_scl=scaler.fit_transform(X_train)#mean and SD
X_tst_scl=scaler.transform(X_test)
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsRegressor(n_neighbors=k) 
    knn.fit(X_trn_scl,y_train)
    y_pred=knn.predict(X_tst_scl)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=True)

    K     score
0   1  0.618293
1   2  0.649537
9  10  0.684710
3   4  0.687542
8   9  0.691397
2   3  0.692301
6   7  0.692776
5   6  0.695438
7   8  0.698523
4   5  0.709663

In [12]:
min_max_scaler=MinMaxScaler()
transf_X_train=min_max_scaler.fit_transform(X_train)
transf_X_test=min_max_scaler.transform(X_test)

Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsRegressor(n_neighbors=k) 
    knn.fit(transf_X_train,y_train)
    y_pred=knn.predict(transf_X_test)
    scores.append([k,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=True)

    K     score
0   1  0.565138
1   2  0.594986
3   4  0.654668
2   3  0.661415
9  10  0.671331
8   9  0.674605
7   8  0.677849
4   5  0.678191
6   7  0.681397
5   6  0.686453