In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.metrics import classification_report,roc_auc_score, log_loss
from sklearn.preprocessing import OneHotEncoder,StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector

In [33]:
img_seg=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Image_Segmentation\\Image_Segmentation.csv")
img_seg

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [34]:
le=LabelEncoder()
img_seg['Class']=le.fit_transform(img_seg['Class'])
X,y=img_seg.drop('Class',axis=1), img_seg['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=img_seg['Class'])

In [35]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsClassifier(n_neighbors=k) 
    knn.fit(X_train,y_train)
    y_pred_prob=knn.predict_proba(X_test)
    scores.append([k,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=True)

    K     score
5   6  0.971258
6   7  0.981489
7   8  1.016964
8   9  1.049631
9  10  1.084273
4   5  1.506703
2   3  1.996419
3   4  2.015082
1   2  3.036645
0   1  4.004850

In [36]:
#With Standard Scaling
scaler=StandardScaler().set_output(transform="pandas")

In [37]:
scaler.fit(X_train)
X_trn_scl=scaler.transform(X_train)#mean and SD
X_tst_scl=scaler.transform(X_test)

In [38]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsClassifier(n_neighbors=k) 
    knn.fit(X_trn_scl,y_train)
    y_pred_prob=knn.predict_proba(X_tst_scl)
    scores.append([k,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=True)

    K     score
7   8  0.352821
8   9  0.381166
9  10  0.399369
5   6  0.815084
6   7  0.856190
2   3  1.257178
3   4  1.301800
4   5  1.322391
1   2  3.465736
0   1  4.004850

In [39]:
min_max_scaler=MinMaxScaler()
transf_X_train=min_max_scaler.fit_transform(X_train)
transf_X_test=min_max_scaler.transform(X_test)

In [41]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsClassifier(n_neighbors=k) 
    knn.fit(transf_X_train,y_train)
    y_pred_prob=knn.predict_proba(transf_X_test)
    scores.append([k,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['K','score'])
df_scores.sort_values('score',ascending=True)

    K     score
2   3  0.165250
3   4  0.197000
4   5  0.256929
5   6  0.281758
6   7  0.304352
7   8  0.343368
8   9  0.385612
9  10  0.400394
1   2  2.332495
0   1  2.860607