In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.metrics import classification_report,roc_auc_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector
from sklearn.naive_bayes import BernoulliNB

In [30]:
cancer=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Cancer\\Cancer.csv",index_col=0)
le=LabelEncoder()
cancer['Class']=le.fit_transform(cancer['Class'])
X,y=cancer.drop('Class', axis=1), cancer['Class']
cancer

,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat,Class
subjid,,,,,,,,,,
1,40-49,premeno,15 to 19,0 to 2,yes,three,right,left_up,no,1
2,50-59,ge40,15 to 19,0 to 2,no,one,right,central,no,0
3,50-59,ge40,35 to 39,0 to 2,no,two,left,left_low,no,1
4,40-49,premeno,35 to 39,0 to 2,yes,three,right,left_low,yes,0
5,40-49,premeno,30 to 34,3 to 5,yes,two,left,right_up,no,1
...,...,...,...,...,...,...,...,...,...,...
282,50-59,ge40,30 to 34,6 to 8,yes,two,left,left_low,no,0
283,50-59,premeno,25 to 29,3 to 5,yes,two,left,left_low,yes,0
284,30-39,premeno,30 to 34,6 to 8,yes,two,right,right_up,no,0
285,50-59,premeno,15 to 19,0 to 2,no,two,right,left_low,no,0
286,50-59,ge40,40 to 44,0 to 2,no,three,left,right_up,no,0

In [31]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=cancer['Class'])

In [32]:
ohe=OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore").set_output(transform="pandas")
X_trn_ohe=ohe.fit_transform(X_train)
X_tst_ohe=ohe.transform(X_test)

C:\Users\PGCP-AI\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [7] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [33]:
nb=BernoulliNB()
nb.fit(X_trn_ohe,y_train)
y_pred_prob=nb.predict_proba(X_tst_ohe)
print("ROC AUC=",roc_auc_score(y_test,y_pred_prob[:,1]))
y_pred=nb.predict(X_tst_ohe)
print("Accuracy=",accuracy_score(y_test,y_pred))

ROC AUC= 0.6958333333333333
Accuracy= 0.7093023255813954

## Telecom

In [34]:
tel=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets\\Telecom.csv")
tel

    Gender TT_gt_100 Response
0        F         Y        N
1        M         N        N
2        M         N        N
3        F         Y        Y
4        F         N        N
..     ...       ...      ...
145      F         Y        Y
146      M         N        Y
147      M         N        N
148      M         N        N
149      F         N        N

[150 rows x 3 columns]

In [35]:
le=LabelEncoder()
tel['Response']=le.fit_transform(tel['Response'])
X,y=tel.drop('Response', axis=1), tel['Response']
tel

    Gender TT_gt_100  Response
0        F         Y         0
1        M         N         0
2        M         N         0
3        F         Y         1
4        F         N         0
..     ...       ...       ...
145      F         Y         1
146      M         N         1
147      M         N         0
148      M         N         0
149      F         N         0

[150 rows x 3 columns]

In [36]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=tel['Response'])

In [37]:
ohe=OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore").set_output(transform="pandas")
X_trn_ohe=ohe.fit_transform(X_train)
X_tst_ohe=ohe.transform(X_test)

In [38]:
nb=BernoulliNB()
nb.fit(X_trn_ohe,y_train)
y_pred_prob=nb.predict_proba(X_tst_ohe)
print("ROC AUC=",roc_auc_score(y_test,y_pred_prob[:,1]))
y_pred=nb.predict(X_tst_ohe)
print("Accuracy=",accuracy_score(y_test,y_pred))

ROC AUC= 0.9140316205533597
Accuracy= 0.9111111111111111