In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from tqdm import tqdm
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.metrics import classification_report,roc_auc_score, log_loss
from sklearn.preprocessing import OneHotEncoder,StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector

In [4]:
train=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Day4\\playground-series-s6e3\\train.csv")
train

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,594189,Male,0,No,No,57,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),97.55,5460.70,No
594190,594190,Female,0,No,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),91.95,6782.15,No
594191,594191,Female,0,Yes,No,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.40,1871.90,No
594192,594192,Female,0,No,No,32,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,86.00,2847.20,No
594193,594193,Female,1,Yes,No,2,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,54.55,108.05,Yes

In [10]:
X,y=train.drop('Churn',axis=1), train['Churn']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=train['Churn'])

In [11]:
ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
transf=ColumnTransformer(transformers=[("OHE",ohe, make_column_selector
                                        (dtype_include=object))],remainder="passthrough",verbose_feature_names_out=False).set_output(transform="pandas")
X_trn_ohe=transf.fit_transform(X_train)
X_tst_ohe=transf.transform(X_test)
le=LabelEncoder()
train['Churn']=le.fit_transform(train['Churn'])

In [12]:
X_trn_ohe

,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,id,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
433355,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,433355,0,60,107.55,6157.60
299628,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,299628,0,55,74.65,4299.65
72575,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,72575,0,52,111.90,5431.90
433127,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,433127,0,10,19.65,242.75
368061,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,368061,1,15,85.25,1258.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397562,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,397562,0,46,81.50,3369.05
353408,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,353408,0,14,54.55,973.35
398034,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,398034,0,63,19.95,1216.85
564302,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,564302,0,1,55.00,55.00
593785,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,593785,0,66,108.55,7397.00

In [13]:
# Ks=[1,2,3,4,5,6,7,8,9,10]
# scores=[]
# for k in Ks:
#     knn=KNeighborsClassifier(n_neighbors=k) 
#     knn.fit(X_trn_ohe,y_train)
#     y_pred=knn.predict(X_tst_ohe)
#     scores.append([k,r2_score(y_test,y_pred)])
# df_scores=pd.DataFrame(scores,columns=['K','score'])
# df_scores.sort_values('score',ascending=False)

In [14]:
scaler=StandardScaler().set_output(transform="pandas")

In [17]:
scaler.fit(X_trn_ohe)
X_trn_scl=scaler.transform(X_trn_ohe)#mean and SD
X_tst_scl=scaler.transform(X_tst_ohe)

In [19]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in tqdm(Ks):
    knn=KNeighborsClassifier(n_neighbors=k) 
    knn.fit(X_trn_scl,y_train)
    y_pred_prob=knn.predict_proba(X_tst_scl)
    scores.append([k,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['K','score'])

100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [25:19<00:00, 151.96s/it]

In [20]:
df_scores.sort_values('log_loss',ascending=True)

KeyError: 'log_loss'