# Text Classification

In [1]:
from transformers import pipeline

C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import torch
print(torch.__version__)

2.12.0+cpu

# Text Classification

In [4]:
classifier=pipeline('text-classification')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

WARNING:tensorflow:From C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [5]:
import pandas as pd

In [6]:
text='It was possible for him. So he did it.'

In [7]:
result=classifier(text)

In [8]:
df=pd.DataFrame(result)

In [9]:
text='Nothing is possible without these efforts!'
result=classifier(text)
df=pd.DataFrame(result)
df

      label     score
0  POSITIVE  0.994458

In [10]:
text='It was so impressive but not upto the mark.'
result = classifier(text)
df = pd.DataFrame(result)
df

      label     score
0  NEGATIVE  0.983271

In [11]:
text = '''disney's 35th animated feature-- a retooling of the olympian legend
great wit , great art , and a great villain ( james woods as hades , lord of th
( none of the alan menken/david zippel tunes are particular- ly noteworthy .
some lack lyrical snap .
others need more memorable melodies .
boring ballads we expect , but boring production numbers , too ? )
so , hercules is a bit of a long sit , but you won't stay bored .
the highlights include a nifty round of animated action ( herc battling a cgi h
while not as rock-solid as hunchback , it's a still a new world of improvement
directed by ron clements and john musker , with voice credits including tate do'''
result = classifier(text)
df = pd.DataFrame(result)
df

      label     score
0  POSITIVE  0.993177

In [12]:
text = '''The story follows a disgraced spy on the run, but the narrative is so convoluted that it barely functions on a basic level. Instead of logical progression, the audience is subjected to disjointed flashbacks, unnecessary subplots, and "villains" whose motivations are never fully explained. The stakes feel completely hollow because the director relies on cheap, illogical shortcuts to move the story from one explosion to the next.'''
result = classifier(text)
df = pd.DataFrame(result)
df

      label     score
0  NEGATIVE  0.999805

# Name Entity  Recognition

In [13]:
ner = pipeline('token-classification')
text='''
Ratan Naval Tata[a] (28 December 1937 – 9 October 2024) was an Indian industrialist and philanthropist. He served as the chairman of Tata Group
and Tata Sons from 1991 to 2012, and he held the position of the interim chairman from October 2016 to February 2017.[3][4] In 2000, he received the Padma Bhushan,
the third-highest civilian honour in India, followed by the Padma Vibhushan, the country's second-highest civilian honour, in 2008.[5]

Ratan Tata was the son of Naval Tata, who was adopted by Ratanji Tata, son of Jamsetji Tata, the founder of the Tata Group.
 He graduated from Cornell University College of Architecture with a bachelor's degree in architecture.[6]
  He had also attended the Harvard Business School Advanced Management Program in 1975.[2] He joined the Tata Group in 1962,[7] starting on the shop floor of Tata Steel.
   He later succeeded JRD Tata as chairman of Tata Sons upon the latter's retirement in 1991. During
his tenure, the Tata Group acquired Tetley, Jaguar Land Rover, and Corus, in an attempt to t
urn Tata from a largely India-centric group into a global business
'''

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [14]:
result = ner(text)
df = pd.DataFrame(result)
df

    entity     score  index   word  start   end
0    I-PER  0.998451      1    Rat      1     4
1    I-PER  0.998594      2   ##an      4     6
2    I-PER  0.999082      3  Naval      7    12
3    I-PER  0.999123      4     Ta     13    15
4    I-PER  0.996838      5   ##ta     15    17
..     ...       ...    ...    ...    ...   ...
74   I-ORG  0.998070    247     Co   1014  1016
75   I-ORG  0.997786    248  ##rus   1016  1019
76   I-ORG  0.994389    257     Ta   1044  1046
77   I-ORG  0.995759    258   ##ta   1046  1048
78  I-MISC  0.922444    262  India   1064  1069

[79 rows x 6 columns]

# Question answering

In [15]:
qa = pipeline('question-answering')

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [16]:
text = 'New Delhi is capital city of India'
question = 'What is capital city of India?'
result = qa(question=question, context=text)
df = pd.DataFrame([result])
df

      score  start  end     answer
0  0.996726      0    9  New Delhi

In [17]:
text = '''
Antarctica (/ænˈtɑːrktɪkə/ ⓘ)[note 1] is Earth's southernmost and least-populated continent. Situated almost entirely south of the Antarctic Circle and surrounded by the Southern Ocean (also known as the Antarctic Ocean), it contains the geographic South Pole. Antarctica is the fifth-largest continent, being about 40% larger than Europe, and has an area of 14,200,000 km2 (5,500,000 sq mi). Most of Antarctica is covered by the Antarctic ice sheet, with an average thickness of 1.9 km (1.2 mi).

Antarctica is, on average, the coldest, driest, and windiest of the continents, and has the highest average elevation. It is mainly a polar desert, with annual precipitation of over 200 mm (8 in) along the coast and far less inland. About 70% of the world's freshwater reserves are frozen in Antarctica, which, if melted, would raise global sea levels by almost 60 metres (200 ft). Antarctica holds the record for the lowest measured temperature on Earth, −89.2 °C (−128.6 °F). The coastal regions can reach temperatures over 10 °C (50 °F) in the summer. Native species of animals include mites, nematodes, penguins, seals and tardigrades. Where vegetation occurs, it is mostly in the form of lichen or moss.

The ice shelves of Antarctica were probably first seen in 1820, during a Russian expedition led by Fabian Gottlieb von Bellingshausen and Mikhail Lazarev. The decades that followed saw further exploration by French, American, and British expeditions. The first confirmed landing was by a Norwegian team in 1895. In the early 20th century, there were a few expeditions into the interior of the continent. British explorers Douglas Mawson, Edgeworth David, and Alistair Mackay were the first to reach the magnetic South Pole in 1909, and the geographic South Pole was first reached in 1911 by Norwegian explorer Roald Amundsen.

Antarctica is governed by about 30 countries, all of which are parties of the 1959 Antarctic Treaty System. According to the terms of the treaty, military activity, mining, nuclear explosions, and nuclear waste disposal are all prohibited in Antarctica. Tourism, fishing and research are the main human activities in and around Antarctica. During the summer months, about 5,000 people reside at research stations, a figure that drops to around 1,000 in the winter. Despite the continent's remoteness, human activity has a significant effect on it via pollution, ozone depletion, and climate change. The melting of the potentially unstable West Antarctic ice sheet causes the most uncertainty in century-scale projections of sea level rise, and the same melting also affects the Southern Ocean overturning circulation, which can eventually lead to significant impacts on the Southern Hemisphere climate and Southern Ocean productivity.

Etymology'''
question = 'Antartica is governed by how many countries?'
result = qa(question=question, context=text)
df = pd.DataFrame([result])
df

      score  start   end answer
0  0.453028   1868  1870     30

In [18]:
question1 = 'How many penguins are there in antartica?'
result = qa(question=question1, context=text)
df = pd.DataFrame([result])
df

      score  start   end answer
0  0.000103   2280  2285  1,000

# Translation

In [19]:
trans = pipeline('translation_en_to_fr')

No model was supplied, defaulted to google-t5/t5-base and revision 686f1db (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\transformers\models\t5\tokenization_t5_fast.py:171: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on google-t5/t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(

In [29]:
translator = pipeline(
    'translation',
    model='facebook/m2m100_418M',
    src_lang='en',
    tgt_lang='mr'
)

text = "The quick brown fox jumps over the lazy dog"
# text='where is Sai? did she ate apple'
result = translator(text)

# Changed 'translated_text' to 'translation_text'
print("Translated text: ", result[0]['translation_text'])

Translated text:  त्वरित ब्राउन फॉक्स कुत्र्यावर जातो.

In [34]:
text = "Shraddha is a good girl"
result = translator(text)
print("Translated text: ", result[0]['translation_text'])

Translated text:  श्रीदेवी चांगली मुलगी आहे.

# Text generation

In [35]:
generator= pipeline('text-generation')
data = generator('I want to learn Python Programmimg so',
                 max_length = 30, num_return_sequences = 2)

No model was supplied, defaulted to openai-community/gpt2 and revision 6c0e608 (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.
C:\Users\PGCP-AI\AppData\Local\anaconda3\envs\tf_env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\PGCP-AI\.cache\huggingface\hub\models--openai-community--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [37]:
for sent in data:
  print(sent)
  print()

{'generated_text': "I want to learn Python Programmimg so much it will make me laugh.\n\n[6:02PM] Warning: File 'python3"}

{'generated_text': 'I want to learn Python Programmimg so I can use it all day.\n\nThere is code out there so if you want to add one'}

# Visual Question Answering