In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("booking_data.csv")
df

      Unnamed: 0  bookingid
0              0       1138
1              1       1609
2              2        431
3              3       1475
4              4       1702
...          ...        ...
2139        2139       1416
2140        2140       2928
2141        2141        243
2142        2142        254
2143        2143       1679

[2144 rows x 2 columns]

In [7]:
filt=df["bookingid"]==821
df.loc[filt,:]

      Unnamed: 0  bookingid
1512        1512        821

In [8]:
df=pd.read_csv("book_data.csv")
df

,Unnamed: 0,firstname,lastname,totalprice,depositpaid,bookingdates,additionalneeds
0,checkin,Jane,Doe,111,True,2018-01-01,Extra pillows please
1,checkout,Jane,Doe,111,True,2019-01-01,Extra pillows please