In [24]:
import numpy as np
import os
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
os.chdir("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Concrete_Strength")

In [25]:
concretedata=pd.read_csv("Concrete_Data.csv")
concretedata

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [26]:
X=concretedata.drop("Strength",axis=1)
y=concretedata["Strength"]
# poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
# X_poly=poly.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_poly,y,test_size=0.3,random_state=26)
# lr=LinearRegression()
# lr.fit(X_train,y_train)
# y_pred=lr.predict(X_test)
# print("MAE=",mean_absolute_error(y_test,y_pred))
# print("MSE=",root_mean_squared_error(y_test,y_pred))
# print("R2=",r2_score(y_test,y_pred))

In [19]:
# poly=PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
# X_poly=poly.fit_transform(X)
# X_train,X_test,y_train,y_test=train_test_split(X_poly,y,test_size=0.3,random_state=26)
# lr=LinearRegression()
# lr.fit(X_train,y_train)
# y_pred=lr.predict(X_test)
# print("MAE=",mean_absolute_error(y_test,y_pred))
# print("MSE=",root_mean_squared_error(y_test,y_pred))
# print("R2=",r2_score(y_test,y_pred))

In [27]:
ridge=Ridge()
ridge.fit(X_train,y_train)
y_pred=ridge.predict(X_test)
print(ridge.coef_)
print("R2=",r2_score(y_test,y_pred))

[ 1.78893880e+00  1.28187027e+00  5.71797833e-01  8.78082085e+00
  1.19750076e+01  1.25618694e+00  2.30541593e+00  5.73648278e-03
 -3.13611515e-04 -3.91729501e-04  5.34037551e-05 -3.33854716e-03
 -5.39576016e-03 -3.13386436e-04 -6.98024987e-04  1.86830366e-04
 -2.07110613e-04  2.80701067e-04 -2.56593926e-03 -4.45949751e-03
 -2.79877258e-04 -4.07770075e-04  4.40294773e-04  2.79394813e-04
 -2.67197493e-03 -9.68794628e-03  1.97496904e-05 -1.01960572e-04
  6.75437854e-04 -5.55418700e-03 -8.67344617e-03 -2.88250791e-03
 -3.66900052e-03  2.65440079e-04 -3.13357856e-02 -3.93650169e-03
 -4.27678463e-03  2.33461423e-03 -9.93310882e-05 -5.21944061e-04
 -6.90823602e-05 -5.71745408e-04  2.74923502e-04 -6.06819901e-04]
R2= 0.8106426487738103

In [31]:
alphas=np.linspace(0.001,10)
scores=[]
for a in alphas:
    ridge=Ridge(alpha=a)
    ridge.fit(X_train,y_train)
    y_pred=ridge.predict(X_test)
    scores.append([a,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=["alpha","score"])
df_scores.sort_values(by="score",ascending=False)

        alpha     score
0    0.001000  0.811700
1    0.205061  0.811677
2    0.409122  0.811412
3    0.613184  0.811122
4    0.817245  0.810856
5    1.021306  0.810619
6    1.225367  0.810412
7    1.429429  0.810229
8    1.633490  0.810068
9    1.837551  0.809923
10   2.041612  0.809794
11   2.245673  0.809676
12   2.449735  0.809569
13   2.653796  0.809471
14   2.857857  0.809381
15   3.061918  0.809298
16   3.265980  0.809220
17   3.470041  0.809148
18   3.674102  0.809081
19   3.878163  0.809017
20   4.082224  0.808958
21   4.286286  0.808902
22   4.490347  0.808849
23   4.694408  0.808799
24   4.898469  0.808751
25   5.102531  0.808706
26   5.306592  0.808662
27   5.510653  0.808621
28   5.714714  0.808582
29   5.918776  0.808544
30   6.122837  0.808508
31   6.326898  0.808474
32   6.530959  0.808441
33   6.735020  0.808409
34   6.939082  0.808378
35   7.143143  0.808349
36   7.347204  0.808320
37   7.551265  0.808293
38   7.755327  0.808266
39   7.959388  0.808241
40   8.163449  0.808216
41   8.367510  0.808192
42   8.571571  0.808169
43   8.775633  0.808147
44   8.979694  0.808125
45   9.183755  0.808104
46   9.387816  0.808083
47   9.591878  0.808063
48   9.795939  0.808044
49  10.000000  0.808025