In [1]:
import numpy as np
import os
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
os.chdir("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets")

In [2]:
pizza=pd.read_csv("pizza.csv")
pizza

    Promote  Sales
0        23    554
1        56   1339
2        34    815
3        25    609
4        67   1600
5        82   2000
6        46   1000
7        14    300
8         6    150
9        47   1150
10       52   1200
11       88   2000
12       71   1750
13       78   2000
14       66   1500
15       44   1000
16       68   1600
17       90   2000
18       22    550

In [3]:
X=pizza[["Promote"]]
y=pizza["Sales"]
lr=LinearRegression()
lr.fit(X,y)

LinearRegression()

In [4]:
lr.coef_,lr.intercept_

(array([23.50640302]), np.float64(5.4858653632529695))

In [5]:
boston=pd.read_csv("Boston.csv")
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print("MAE=",mean_absolute_error(y_test,y_pred))
print("MSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

MAE= 51.22256690060802
MSE= 58.06505794709233
R2= 0.9922406370875262

In [7]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
lr=LinearRegression()
lr.fit(X_poly,y)
lr.coef_, lr.intercept_

(array([ 2.48006959e+01, -1.30947333e-02]), np.float64(-18.27491741664585))

In [8]:
insure=pd.read_csv("Insure_auto.csv")
X=insure[["Home","Automobile"]]
y=insure["Operating_Cost"]
poly=PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_poly

,Home,Automobile,Home^2,Home Automobile,Automobile^2,Home^3,Home^2 Automobile,Home Automobile^2,Automobile^3
0,400.0,1200.0,160000.0,480000.0,1440000.0,64000000.0,1.920000e+08,5.760000e+08,1.728000e+09
1,350.0,360.0,122500.0,126000.0,129600.0,42875000.0,4.410000e+07,4.536000e+07,4.665600e+07
2,600.0,800.0,360000.0,480000.0,640000.0,216000000.0,2.880000e+08,3.840000e+08,5.120000e+08
3,800.0,1800.0,640000.0,1440000.0,3240000.0,512000000.0,1.152000e+09,2.592000e+09,5.832000e+09
4,900.0,1600.0,810000.0,1440000.0,2560000.0,729000000.0,1.296000e+09,2.304000e+09,4.096000e+09
5,200.0,1000.0,40000.0,200000.0,1000000.0,8000000.0,4.000000e+07,2.000000e+08,1.000000e+09
6,120.0,900.0,14400.0,108000.0,810000.0,1728000.0,1.296000e+07,9.720000e+07,7.290000e+08
7,340.0,1100.0,115600.0,374000.0,1210000.0,39304000.0,1.271600e+08,4.114000e+08,1.331000e+09
8,490.0,900.0,240100.0,441000.0,810000.0,117649000.0,2.160900e+08,3.969000e+08,7.290000e+08
9,700.0,800.0,490000.0,560000.0,640000.0,343000000.0,3.920000e+08,4.480000e+08,5.120000e+08

In [9]:
boston=pd.read_csv("Boston.csv")
X=boston.drop("medv",axis=1)
y=boston["medv"]
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_poly,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print("R2=",r2_score(y_test,y_pred))

R2= 0.6657958510458925

In [10]:
housing=pd.read_csv("Housing.csv")
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [11]:
dum_hous=pd.get_dummies(housing,dtype=int,drop_first=True)
print(dum_hous)
X,y=dum_hous.drop("price",axis=1),dum_hous["price"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print("R2=",r2_score(y_test,y_pred))

        price  lotsize  bedrooms  bathrms  stories  garagepl  driveway_yes  \
0     42000.0     5850         3        1        2         1             1
1     38500.0     4000         2        1        1         0             1
2     49500.0     3060         3        1        1         0             1
3     60500.0     6650         3        1        2         0             1
4     61000.0     6360         2        1        1         0             1
..        ...      ...       ...      ...      ...       ...           ...
541   91500.0     4800         3        2        4         0             1
542   94000.0     6000         3        2        4         0             1
543  103000.0     6000         3        2        4         1             1
544  105000.0     6000         3        2        2         1             1
545  105000.0     6000         3        1        2         1             1

     recroom_yes  fullbase_yes  gashw_yes  airco_yes  prefarea_yes
0              0             1          0          0             0
1              0             0          0          0             0
2              0             0          0          0             0
3              1             0          0          0             0
4              0             0          0          0             0
..           ...           ...        ...        ...           ...
541            1             0          0          1             0
542            0             0          0          1             0
543            1             0          0          1             0
544            1             0          0          1             0
545            0             0          0          1             0

[546 rows x 12 columns]
R2= 0.6791781818067918

In [12]:
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_poly,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print("MAE=",mean_absolute_error(y_test,y_pred))
print("MSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

MAE= 12846.311771121402
MSE= 19729.548845663983
R2= 0.4488658162767213

In [13]:
poly=PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
X_poly=poly.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_poly,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print("MAE=",mean_absolute_error(y_test,y_pred))
print("MSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

MAE= 28178.568083848044
MSE= 94822.93659640719
R2= -11.730628410247519

In [14]:
chem=pd.read_csv("ChemicalProcess.csv")
chem

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019,0.5,3,7.2,NaN,NaN,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019,2.0,2,7.2,0.1,0.15,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,0.7,2,7.2,0.0,0.00,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,1.2,2,7.2,0.0,0.00,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017,0.2,2,7.3,0.0,0.00,11.0,1.1,1.7,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,39.66,6.71,56.32,66.19,12.35,20.02,50.26,100.0,17.54,12.50,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
172,39.68,6.87,56.74,66.61,12.55,20.18,50.80,100.0,17.48,12.41,...,NaN,1.0,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
173,42.23,7.50,58.41,68.30,13.33,20.81,52.96,100.0,17.23,12.04,...,NaN,1.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
174,38.48,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.5,0.0,0.0
175,39.49,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,0.9,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0

In [15]:
chem.isnull().sum().sum()

np.int64(106)

In [16]:
chem.shape

(176, 58)

In [17]:
X,y=chem.drop("Yield",axis=1),chem["Yield"]
mean_imp=SimpleImputer(strategy="mean")
med_imp=SimpleImputer(strategy="median")
X_imp=mean_imp.fit_transform(X)
X_train,X_test,y_train,y_test=train_test_split(X_imp,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
# print("MAE=",mean_absolute_error(y_test,y_pred))
# print("MSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

R2= -5.170497655271503

In [18]:
mean_imp=SimpleImputer(strategy="mean").set_output(transform="pandas")
X_trn_imp=mean_imp.fit_transform(X_train)
X_tst_imp=mean_imp.transform(X_test)
lr.fit(X_trn_imp,y_train)
y_pred=lr.predict(X_tst_imp)
print("R2=",r2_score(y_test,y_pred))

R2= -5.170497655271503

In [23]:
med_imp=SimpleImputer(strategy="median").set_output(transform="pandas")
X_trn_imp=med_imp.fit_transform(X_train)
X_tst_imp=med_imp.transform(X_test)
lr.fit(X_trn_imp,y_train)
y_pred=lr.predict(X_tst_imp)
print("R2=",r2_score(y_test,y_pred))

R2= -5.170497655271503