## regression pronblem

In [23]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
# from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score,log_loss,r2_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression,LinearRegression,ElasticNet
from sklearn.ensemble import BaggingRegressor
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector
from tqdm import tqdm
from sklearn.neighbors import KNeighborsRegressor

In [24]:
concrete=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Concrete_Strength\\Concrete_Data.csv")
concrete

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [30]:
X,y=concrete.drop("Strength",axis=1),concrete["Strength"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)

In [31]:
le=LinearRegression()
el=ElasticNet()
knn=KNeighborsRegressor()
dtr=DecisionTreeRegressor(random_state=26)


scores=[]
estmes=[le,el,knn,dtr]
for e in tqdm(estmes):
    for n in [10,15,50,100]:
        bagg=BaggingRegressor(random_state=26,estimator=e,n_estimators=n)
        bagg.fit(X_train,y_train)
        y_pred=bagg.predict(X_test)
        scores.append([e,n,r2_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=["Model","n_est","score"])
df_scores.sort_values("score",ascending=True)

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]

                                     Model  n_est     score
2                       LinearRegression()     50  0.617486
6                             ElasticNet()     50  0.618041
3                       LinearRegression()    100  0.618434
1                       LinearRegression()     15  0.618851
7                             ElasticNet()    100  0.618955
5                             ElasticNet()     15  0.619367
0                       LinearRegression()     10  0.619629
4                             ElasticNet()     10  0.620164
9                    KNeighborsRegressor()     15  0.675296
8                    KNeighborsRegressor()     10  0.678554
10                   KNeighborsRegressor()     50  0.680985
11                   KNeighborsRegressor()    100  0.683729
13  DecisionTreeRegressor(random_state=26)     15  0.894110
12  DecisionTreeRegressor(random_state=26)     10  0.894547
14  DecisionTreeRegressor(random_state=26)     50  0.897347
15  DecisionTreeRegressor(random_state=26)    100  0.898804