In [1]:
import numpy as np
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
os.chdir("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets")

In [2]:
house=pd.read_csv("Housing.csv")
house

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [6]:
X=house.drop("Price",axis=1)
y=house["Price"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print("MAE=",mean_absolute_error(y_test,y_pred))
print("MSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

KeyError: "['Price'] not found in axis"

In [3]:
dum_tst=pd.get_dummies(house)
dum_tst

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_no,driveway_yes,recroom_no,recroom_yes,fullbase_no,fullbase_yes,gashw_no,gashw_yes,airco_no,airco_yes,prefarea_no,prefarea_yes
0,42000.0,5850,3,1,2,1,False,True,True,False,False,True,True,False,True,False,True,False
1,38500.0,4000,2,1,1,0,False,True,True,False,True,False,True,False,True,False,True,False
2,49500.0,3060,3,1,1,0,False,True,True,False,True,False,True,False,True,False,True,False
3,60500.0,6650,3,1,2,0,False,True,False,True,True,False,True,False,True,False,True,False
4,61000.0,6360,2,1,1,0,False,True,True,False,True,False,True,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,False,True,False,True,True,False,True,False,False,True,True,False
542,94000.0,6000,3,2,4,0,False,True,True,False,True,False,True,False,False,True,True,False
543,103000.0,6000,3,2,4,1,False,True,False,True,True,False,True,False,False,True,True,False
544,105000.0,6000,3,2,2,1,False,True,False,True,True,False,True,False,False,True,True,False
545,105000.0,6000,3,1,2,1,False,True,True,False,True,False,True,False,False,True,True,False

In [4]:
bm=LinearRegression()
bm.fit(X,y)
X.columns

NameError: name 'X' is not defined

In [7]:
dum_tst['driveway_yes']=[True, True, True, True]
dum_tst['gashw_yes']=False
dum_tst['airco_yes']=False
dum_tst['prefarea_yes']=False
dum_tst=dum_tst[['lotsize','bedrooms','bathrms','stories','garagepl','driveway_yes','recroom_yes',
                'fullbase_yes','gashw_yes','airco_yes','prefarea_yes']]
dum_tst.columns

ValueError: Length of values (4) does not match length of index (546)