In [6]:
import pandas as pd
import numpy as np
import os
os.chdir("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets")

In [10]:
ords=pd.read_csv("Orders.csv",parse_dates=["Order Date"])
ords

C:\Users\PGCP-AI\AppData\Local\Temp\ipykernel_21400\383233910.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ords=pd.read_csv("Orders.csv",parse_dates=["Order Date"])

     Order ID Order Date Place of Shipment Mode of Payment
0   32 90 001 2010-12-31              Pune          Cheque
1   32 90 002 2011-01-06             Nasik          Online
2   32 90 003 2011-01-14        Ahmednagar            Cash
3   32 90 004 2011-02-18            Nanded          Cheque
4   32 90 005 2011-02-19          Kolhapur            Cash
..        ...        ...               ...             ...
65  32 90 066 2013-07-13          Nadurbar          Cheque
66  32 90 067 2013-07-23             Dhule          Cheque
67  32 90 068 2013-08-02         Ratnagiri          Online
68  32 90 069 2013-09-04             Dhule          Cheque
69  32 90 070 2013-09-07         Ratnagiri          Cheque

[70 rows x 4 columns]

In [11]:
ords.dtypes

Order ID                        str
Order Date           datetime64[us]
Place of Shipment               str
Mode of Payment                 str
dtype: object

In [12]:
ords["year"]=ords["Order Date"].dt.year
ords["month"]=ords["Order Date"].dt.month
ords["day"]=ords["Order Date"].dt.day
ords["weekday"]=ords["Order Date"].dt.weekday

In [13]:
ords

,Order ID,Order Date,Place of Shipment,Mode of Payment,year,month,day,weekday
0,32 90 001,2010-12-31,Pune,Cheque,2010,12,31,4
1,32 90 002,2011-01-06,Nasik,Online,2011,1,6,3
2,32 90 003,2011-01-14,Ahmednagar,Cash,2011,1,14,4
3,32 90 004,2011-02-18,Nanded,Cheque,2011,2,18,4
4,32 90 005,2011-02-19,Kolhapur,Cash,2011,2,19,5
...,...,...,...,...,...,...,...,...
65,32 90 066,2013-07-13,Nadurbar,Cheque,2013,7,13,5
66,32 90 067,2013-07-23,Dhule,Cheque,2013,7,23,1
67,32 90 068,2013-08-02,Ratnagiri,Online,2013,8,2,4
68,32 90 069,2013-09-04,Dhule,Cheque,2013,9,4,2
69,32 90 070,2013-09-07,Ratnagiri,Cheque,2013,9,7,5