In [26]:
import numpy as np
import pandas as pd
import os
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,recall_score,precision_score,classification_report
os.chdir("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Wisconsin")

In [27]:
cancer=pd.read_csv("BreastCancer.csv")
cancer

,Code,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
0,61634,5,4,3,1,2,2,2,3,1,Benign
1,63375,9,1,2,6,4,10,7,7,2,Malignant
2,76389,10,4,7,2,2,8,6,1,1,Malignant
3,95719,6,10,10,10,8,10,7,10,7,Malignant
4,128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...
694,1369821,10,10,10,10,5,10,10,10,7,Malignant
695,1371026,5,10,10,10,4,10,5,6,3,Malignant
696,1371920,5,1,1,1,2,1,3,2,1,Benign
697,8233704,4,1,1,1,1,1,2,1,1,Benign
698,13454352,1,1,3,1,2,1,2,1,1,Benign

In [30]:
X,y=cancer.drop(["Code","Class"],axis=1),cancer["Class"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=cancer['Class'])

solvers=["lbfgs","liblinear","newton-cg","newton-choesky","sag","saga"]
scores=[]
for s in solvers:
    lr=LogisticRegression()
    lr.fit(X_train,y_train)
    y_pred=lr.predict(X_test)
    scores.append([s,f1_score(y_test,y_pred,average="macro")])
df_scores=pd.DataFrame(scores,columns=["solver","score"]) 
df_scores.sort_values("score",ascending=False)

           solver     score
0           lbfgs  0.958004
1       liblinear  0.958004
2       newton-cg  0.958004
3  newton-choesky  0.958004
4             sag  0.958004
5            saga  0.958004

In [31]:
tst=pd.read_csv("tst_cancer.csv")
tst=tst.drop("Code",axis=1)

In [32]:
bm=LogisticRegression(solver="liblinear",C=0.2604105)
bm.fit(X,y)
tst["predicted"]=bm.predict(tst)
tst

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,predicted
0,5,4,3,1,3,2,2,3,10,Benign
1,9,1,2,6,7,2,7,7,2,Benign
2,9,4,8,2,2,4,6,1,1,Malignant
3,5,10,10,10,8,7,1,10,7,Malignant
4,1,10,1,1,2,5,5,1,1,Malignant
5,7,6,4,5,3,9,1,1,2,Malignant